---
title: "How to Wow with R"
subtitle: "A brief introduction generating satisfying outputs"
author: "Matthew Suderman (slide credits: Luke McGuinness)"
date: "Last updated: `r Sys.Date()`"
output:
  xaringan::moon_reader:
    self_contained: true
    css: 
      - "default"
      - "custom.css"
    lib_dir: libs
    nature:
      ratio: '16:9'
      highlightStyle: github
      highlightLines: true
      highlightLanguage: ["r"]
      countIncrementalSlides: false
    seal: false
---

```{r render, eval=F, echo=F}
library(rmarkdown)
library(xaringan)
library(GGally)
library(ggforce)
render("how-to-wow.rmd")
```

```{r knitr, include=FALSE, cache=FALSE}
library(knitr)
knitr::read_chunk('how-to-wow.r')
```

```{r options, include=FALSE, cache=F}
```

```{r, include=FALSE, cache=F}
slides <- c(
    "title.rmd"
    , "topics.rmd"
    , "ggplot2-title.rmd"
    , "ggplot2.rmd"
    , "bmi2.rmd"
    , "ggplot2-christmas.rmd"
    , "ggplot2-christmas8.rmd"
    , "ggplot2-christmas2.rmd"
    , "ggplot2-customisability.rmd"
    #, "ggplot2-stunning.rmd"
    #, "ggplot2-recap.rmd"
    #, "rmd-title.rmd"
    #, "rmd.rmd"
    #, "rmd-components.rmd"
    #, "rmd-example.rmd"
    #, "rmd-pros.rmd"
    #, "rmd-documents.rmd"
    #, "rmd-resources.rmd"
    #, "shiny-title.rmd"
    #, "shiny.rmd"
    #, "shiny-structure.rmd"
    #, "shiny-example.rmd"
    #, "shiny-system.rmd"
    #, "shiny-pros.rmd"
    #, "shiny-resources.rmd"
    #, "pkg-title.rmd"
    #, "pkg-why.rmd"
    #, "pkg-example.rmd"
    #, "pkg-where.rmd"
    #, "pkg-resources.rmd"
    #, "wrapping-up.rmd"
    #, "community.rmd"
    #, "credits.rmd"
    )
slides <- file.path("slides", slides)
```

```{r, child=slides}
```




